plugins {
    id "com.github.node-gradle.node" version "2.0.0"
}

node {
    version = '10.15.0' // https://nodejs.org/en/
    yarnVersion = '1.13.0' // https://yarnpkg.com/en/
    download = true
}

tasks.register('bootRun') {
    dependsOn 'start'
    group = 'application'
    description = 'Run the client app (for use with gradle bootRun -parallel'
}

tasks.register('start', YarnTask) {
    dependsOn 'yarn'
    group = 'application'
    description = 'Run the client app'
    args = ['run', 'start']
}

tasks.register('build', YarnTask) {
    dependsOn 'yarn'
    group = 'build'
    description = 'Build the client bundle'
    args = ['run', 'build']
}

tasks.register('test', YarnTask) {
    dependsOn 'yarn'
    group = 'verification'
    description = 'Run the client tests'
    args = ['run', 'test']
}

tasks.register('eject', YarnTask) {
    dependsOn 'yarn'
    group = 'other'
    description = 'Eject from the create-react-app scripts'
    args = ['run', 'eject']
}
